language: cpp

compiler: gcc

before_install:
  - sudo apt-get -qq install cmake build-essential python libgsl0-dev libboost-all-dev libxerces-c2-dev xsdcxx zlib1g-dev libboinc-app-dev

install:
  - mkdir build && cd build
  - cmake .. -DOM_BOINC_INTEGRATION=ON

script:
  - make -j2
  - ctest -j2
  - export REL="CERN-release"
  - export ARCHIVE="openMalaria-CERN-"`uname -s`"-"`uname -i`".tar.gz"
  - mkdir ${REL}
  - cp openMalaria test/densities.csv ${REL}/
  - cp schema/scenario_current.xsd ${REL}/scenario_33.xsd
  - tar cvzf ${ARCHIVE} ${REL}

notifications:
  email:
    - tobias.thuering@unibas.ch

deploy:
  provider: releases
  api_key:
    secure: dOTDLZ10UHm3JoKODtlBMxChFaXOekUM69S2f6eoAt0ctjFPZXHic2aEUvabeZJqq8UX83xO1I0tGTX7DWMvxd7zPTQHcW9N3XxWvgChKxs4OSqRL7GnunI3iZPH8125ZCeMNuh+oCgf1DdfOy0uOgdygGKzvIYEFhd7c5gOH/I=
  skip_cleanup: true
  file:
    ${ARCHIVE}
  on:
    tags: true
