language: cpp

compiler: gcc

before_install:
  - sudo apt-get -qq install cmake build-essential python libgsl0-dev libboost-all-dev libxerces-c2-dev xsdcxx zlib1g-dev libboinc-app-dev

install:
  - mkdir build && cd build
  - cmake .. -DOM_BOINC_INTEGRATION=ON

script:
  - make -j2
  - ctest -j2
  - pwd
  - find .

notifications:
  email:
    - tobias.thuering@unibas.ch

deploy:
  provider: releases
  api_key:
    secure: dOTDLZ10UHm3JoKODtlBMxChFaXOekUM69S2f6eoAt0ctjFPZXHic2aEUvabeZJqq8UX83xO1I0tGTX7DWMvxd7zPTQHcW9N3XxWvgChKxs4OSqRL7GnunI3iZPH8125ZCeMNuh+oCgf1DdfOy0uOgdygGKzvIYEFhd7c5gOH/I=
  skip_cleanup: true
  file:
    /home/travis/build/SwissTPH/openmalaria/build/openMalaria
    /home/travis/build/SwissTPH/openmalaria/build/schema/scenario_current.xsd
  on:
    tags: true
