env:
  global:
    - BASE_URL="https://github.com/SwissTPH/openmalaria"

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
    - compiler: clang

sudo: false

language: cpp

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
    - build-essential
    - cmake
    - python
    - libboost-all-dev
    - libgsl0-dev
    - libxerces-c2-dev
    - xsdcxx
    - zlib1g-dev

before_install:
  - test "$TRAVIS_OS_NAME" == "osx" && util/install-dep-osx.sh || echo "not installing osx dependencies"

install:
  - mkdir build && pushd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - make -j2
  - ./openMalaria --version && ldd openMalaria
  - ctest -j
  - popd

after_success:
  - util/generate-checksums.sh build
  - util/build-info.sh | tee travis-build.json

before_deploy:
  - tar cvzf openMalaria-$TRAVIS_OS_NAME.tar.gz build/openMalaria* travis-build.json

deploy:
  provider: releases
  api_key:
    secure: dOTDLZ10UHm3JoKODtlBMxChFaXOekUM69S2f6eoAt0ctjFPZXHic2aEUvabeZJqq8UX83xO1I0tGTX7DWMvxd7zPTQHcW9N3XxWvgChKxs4OSqRL7GnunI3iZPH8125ZCeMNuh+oCgf1DdfOy0uOgdygGKzvIYEFhd7c5gOH/I=
  skip_cleanup: true
  file: openMalaria-$TRAVIS_OS_NAME.tar.gz
  on:
    tags: true

# blacklist
branches:
  except:
    - appveyor-build
    - binary-archive
    
notifications:
  email:
    - tobias.thuering@unibas.ch

