env:
  global:
    - BASE_URL="https://github.com/SwissTPH/openmalaria"

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

sudo: false

language: cpp

compiler: gcc

addons:
  apt:
    packages:
    - build-essential
    - cmake
    - python
    - libboost-all-dev
    - libgsl0-dev
    - libxerces-c2-dev
    - xsdcxx
    - zlib1g-dev

before_install:
  - test "$TRAVIS_OS_NAME" == "osx" \
    && brew update \
    && brew install \
      boost  \
      coreutils \
      cmake  \
      cxxtest  \
      gcc \
      gsl  \
      xerces-c  \
      xsd  \
    || echo "not osx"

install:
  - mkdir build && pushd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - make -j2
  - ./openMalaria --version && ldd openMalaria
  - test "$TRAVIS_OS_NAME" == "linux" \
    && ctest -j2 \
    && md5sum openMalaria | tee openMalaria.md5 \
    && sha256sum openMalaria | tee openMalaria.sha256 \
    || echo "osx test follows"
  - test "$TRAVIS_OS_NAME" == "osx" \
    && ctest -j2 \
    && md5 openMalaria | tee openMalaria.md5 \
    && /usr/local/bin/gsha256sum openMalaria | tee openMalaria.sha256 \
    || echo "linux test has run"
  - popd
after_success:
  - util/build-info.sh | tee travis-build.json
  - test "x$TRAVIS_TAG" == "x" \
    || tar cvzf openMalaria-$TRAVIS_OS_NAME.tar.gz build/openMalaria* travis-build.json \
    && rm -v build/openMalaria{,.sha256,.md5} travis-build.json


notifications:
  email:
    - tobias.thuering@unibas.ch

deploy:
  provider: releases
  api_key:
    secure: dOTDLZ10UHm3JoKODtlBMxChFaXOekUM69S2f6eoAt0ctjFPZXHic2aEUvabeZJqq8UX83xO1I0tGTX7DWMvxd7zPTQHcW9N3XxWvgChKxs4OSqRL7GnunI3iZPH8125ZCeMNuh+oCgf1DdfOy0uOgdygGKzvIYEFhd7c5gOH/I=
  skip_cleanup: true
  file:
    - openMalaria-osx.tar.gz
    - openMalaria-linux.tar.gz
  on:
    tags: true

# blacklist
branches:
  except:
    - appveyor-build
    - binary-archive
    
