language: cpp

compiler: gcc

before_install:
  - sudo apt-get -qq install cmake build-essential python libgsl0-dev libboost-all-dev libxerces-c2-dev xsdcxx zlib1g-dev libboinc-app-dev

install:
  - mkdir build && cd build
  - export CXX_FLAGS="-DNO_CHECKSUM_PERTURB -DOM_BOINC_INTEGRATION=ON"
  - if [ -z "$BUILD_TYPE" ]; then export BUILD_TYPE=Release; fi
  - cmake ..

script:
  - make -j2 CXX_FLAGS="${CXX_FLAGS} ${CXX_LINKER_FLAGS}" VERBOSE=1
  - ctest -j2

notifications:
  email:
    - tobias.thuering@unibas.ch

deploy:
  provider: releases
  api_key:
    secure: dOTDLZ10UHm3JoKODtlBMxChFaXOekUM69S2f6eoAt0ctjFPZXHic2aEUvabeZJqq8UX83xO1I0tGTX7DWMvxd7zPTQHcW9N3XxWvgChKxs4OSqRL7GnunI3iZPH8125ZCeMNuh+oCgf1DdfOy0uOgdygGKzvIYEFhd7c5gOH/I=
  skip_cleanup: true
  file:
    build/openMalaria
    build/schema/scenario_current.xsd
  on:
    tags: true
