install:
  - pushd gsl && git submodule init && git submodule update && cmake . & popd
  - dir C:\projects\openmalaria\gsl
  - pushd zlib && git submodule init && git submodule update && cmake . & popd
  - dir C:\projects\openmalaria\zlib
  - mkdir build-win && cd build-win && cmake -DCMAKE_BUILD_TYPE=Release ..
  - tree C:\projects\openmalaria
