clone_depth: 12

environment: 
  VisualStudioVersion: 12.0

cache:
  - xsd-4.0.msi -> appveyor.yml

install:
  - git config --global core.autocrlf true
  - git submodule init && git submodule update
  - pushd util\install-dep-windows\ && install-dependencies-win.bat & popd
  - dir boost_1_55_0\*
  - pushd gsl && cmake . & popd
  - pushd zlib && cmake . & popd
  - mkdir build-win && pushd build-win && cmake .. -DGSL_LIB_OPT:FILEPATH="C:/projects/openmalaria/lib/gsl.lib" -DZ_LIBRARIES:FILEPATH="C:/projects/openmalaria/lib/zlib.lib" -DXERCESC_LIB_OPT:FILEPATH="C:/projects/openmalaria/xsd/lib/vc-12.0/xerces-c_3.lib" -DZ_INCLUDE_DIRS:PATH="C:/projects/openmalaria/zlib" -DXERCESC_INCLUDE_DIRS:PATH="C:/projects/openmalaria/xsd/include/xercesc" -DBoost_INCLUDE_DIR:PATH="C:/projects/openmalaria/boost_1_55_0" -DGSL_INCLUDE_DIR:PATH="C:/projects/openmalaria/gsl" -DGSL_INCLUDE_DIR2:PATH="C:/projects/openmalaria/gsl/gsl" -DGSL_CBLAS_LIB_OPT:FILEPATH="C:/projects/openmalaria/lib/gslcblas.lib" -DXSD_INCLUDE_DIRS:PATH="C:/projects/openmalaria/xsd/include" -DXSD_EXECUTABLE:FILEPATH="C:/projects/openmalaria/xsd/bin/xsd.exe" & popd

configuration: Release

before_build:
  - dir gsl gsl\gsl lib
  - dir gsl\gsl\gsl_vector.h gsl\gsl\gsl_errno.h gsl\gsl\gsl_cdf.h gsl\gsl\gsl_vector_double.h

build:
  project: build-win\OpenMalaria.sln
  parallel: true
  verbosity: normal

after_build:
  - dir build-win\Release\openMalaria.exe
  - build-win\Release\openMalaria.exe --version
  - copy build-win\unittest Release\unittest.exe ..

test_script:
  - build-win\unittest.exe

artifacts:
- path: build-win\Release\openMalaria.exe
- path: build-win\schema\scenario_current.xsd

notifications:
- provider: Email
  to:
  - tobias.thuering@unibas.ch
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: true
