install:
  - pushd C:\projects\openmalaria\gsl; git submodule init; git submodule update; cmake .; popd
  - dir C:\projects\openmalaria\gsl
  - pushd C:\projects\openmalaria\zlib; git submodule init; git submodule update; cmake .; popd
  - dir C:\projects\openmalaria\zlib
